### ISSUE TITLE
기본키의 null 값 오류 발생

### ISSUE THREAD

**Issue by dlwlstks96** [euphony-io/check-in-listener#16]
```kotlin
class ListenRoomData(
    @PrimaryKey val personalNumber: String?,
    @ColumnInfo(name = "address") val address: String?
)
```
```kotiln
    @org.jetbrains.annotations.Nullable
    @androidx.room.PrimaryKey
    private final java.lang.String personalNumber = null;
```

`error: You must annotate primary keys with @NonNull. "personalNumber" is nullable. SQLite considers this a bug and Room does not allow it. See SQLite docs for details`

해당 부분에서 personalNumber는 기본키인듯한데 null 값을
할당하려하니 오류가 나는듯 합니다!!ㅠㅠ

null 값을 넣지 않는 방법이나 personalNumber를 기본키가 아닌
다른 키로 변경하는 방법, 둘 중 하나를 적용해야 할까요??
@Jsueeee @eunzinn

**Comment by Jsueeee** [comment]
아아아아아 맞아요 기본키 그냥 not-null 처리해야합니다!! 제가 놓쳤네요 감사합니다!
그냥 String으로 변경해주세요!!

**Comment by dlwlstks96** [comment]
네 해결했습니다 감사합니다!
