### ISSUE TITLE
리드미 파일 초안 및 수정 방향 논의

### ISSUE THREAD

**Issue by dlwlstks96** [euphony-io/check-in-listener#41]
# Check-in-listener
'Check-in-listener' is a sound wave reception application using the '[euphony](https://github.com/euphony-io/euphony)' library.
It can be used as a facility entry roster in accordance with the COVID-19 Prevention Guidelines.

## Prerequisite
- Allow audio recorder and storage permission to run the app.

![결과01](https://user-images.githubusercontent.com/72801465/136551382-057131f7-6884-46e0-b1fe-272a5e4152c2.jpg) ![결과02](https://user-images.githubusercontent.com/72801465/136551396-d5c9d3ad-80c2-45aa-a5e8-2b47c1e0d0f0.jpg)

## How-to-use
1. Click `방문자 확인 시작하기` button to start receiving sound waves.

![캡처03](https://user-images.githubusercontent.com/72801465/136551418-f6e28c76-9195-4b00-a1f6-9ef2bf5fc017.JPG)

2. If you want to stop receiving sound waves, click `방문자 확인 중지하기` button.

![캡처04](https://user-images.githubusercontent.com/72801465/136350039-0df859d1-de25-4726-8f64-bbf47065423c.JPG)

3. Click `매장 방문 기록 조회` button to check your visit history

![캡처05](https://user-images.githubusercontent.com/72801465/136350067-837ce10e-a589-4952-89f0-ac18ffb99a2b.JPG)

4. `방문 기록 추출하기` button will extract the history of visit to a csv file.

![캡처06](https://user-images.githubusercontent.com/72801465/136555805-e41ac887-38b8-4f1a-99a2-8dd9bfde8e01.JPG)

## Euphony-library

Official Facebook Page : https://www.facebook.com/euphonyproject
Official Library Site : https://dev.jbear.co/euphony

## License
'Check-in-listener' is licensed under the Apache 2.0 license. [License-link](https://github.com/euphony-io/check-in-listener/blob/master/LICENSE)

**Comment by sujin9** [comment]
Click '방문자 확인 시작하기' button to start receiving sound waves.
 보다
 Click  `방문자 확인 시작하기`  button to start receiving sound waves.
 이게 더 보기 깔끔해보일 것 같아요!

**Comment by Jsueeee** [comment]
> Click '방문자 확인 시작하기' button to start receiving sound waves. 보다 Click `방문자 확인 시작하기` button to start receiving sound waves. 이게 더 보기 깔끔해보일 것 같아요!

오 좋은 아이디어입니다 :)
